name: cinnamon_rolls_shop
description: A Flutter app for cinnamon roll shopping.

publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Local asset package
  assets:
    path: assets

  # UI & State Management
  provider: ^6.1.1
  badges: ^3.1.2

  # Utilities & Analysis
  cupertino_icons: ^1.0.2
  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
