name: widgetbook_workspace
description: "Widgetbook setup for cinnamon_rolls_shop."
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Link to the main app and assets package
  cinnamon_rolls_shop:
    path: ../
  assets:
    path: ../assets

  # Widgetbook dependencies
  widgetbook: ^3.11.0
  widgetbook_annotation: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.10.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
